version: '3.8'

services: 
  prestashop-pdf:
    image: prestashop/prestashop:1.7.8.6-apache
    ports:
      - 8006:80
      - 9002:9000
    depends_on:
      - mariadb
    volumes:
      - prestashop-pdf:/var/www/html
      - ./:/var/www/html/modules/webo_pdfgenerator
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb-pdf
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_FOLDER_INSTALL=installDirHasToBeRenamed
      - PS_FOLDER_ADMIN=admin1234
      - PS_LANGUAGE=pl
      - ADMIN_MAIL=support@webo.agency
      - ADMIN_PASSWD=password
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8006

  mariadb-pdf:
    image: mariadb:10.8.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    volumes:
      - db-pdf:/var/lib/mysql

  phpmyadmin-pdf:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports: 
      - 82:81
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

  openssh-server-pdf:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server-pdf
    hostname: openssh-server #optional
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/London
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=prestashop #optional
    volumes:
      - config-pdf:/config
      - prestashop-pdf:/home/prestashop
    ports:
      - 2223:2222
    restart: unless-stopped

volumes:
  prestashop-pdf:
  config-pdf:
  db-pdf:
